### ISSUE TITLE
Auto-detection of serial port

### ISSUE THREAD

**Issue by niels-moller** [tillitis/tkeyclient#14]
The tkey-runapp program features autodetection of the tkey serial port (on my laptop, it automatically selects /dev/ttyACM0, which works fine).

It would be nice if the tkeyclient package also had this autodetect logic.

**Comment by dehanj** [comment]
tkey-runapp uses the functions from tkeyclient to achieve this. 
See ports.go, functions `DetectSerialPort` and `GetSerialPorts` .

**Comment by niels-moller** [comment]
Thanks! I think I was looking at an old checkout where that code was still in internal/util.
